const Community = require("../models/Community");
const Vansh = require("../models/Vansh");
const Kul = require("../models/Kul");
const Khamp = require("../models/Khamp");
const SubKhamp = require("../models/SubKhamp");
const Gotra = require("../models/Gotra");
const cascadeService = require("../services/hierarchyCascadeService");
const {
  HIERARCHY_USER_DETAILS_CLEANUP,
} = require("../utils/hierarchyUserDetailsCleanup");

/**
 * Admin hierarchy entity configuration (Village-pattern CRUD).
 * Used by createHierarchyController() for all six hierarchy levels.
 */
const HIERARCHY_ENTITIES = {
  community: {
    key: "community",
    label: "Community",
    model: Community,
    listFilterParams: [],
    listPopulate: [],
    getByIdPopulate: [],
    duplicateScopeFields: [],
    duplicateMessage: "Community with this name already exists",
    listSuccessMessage: "Communities fetched successfully",
    listFetchErrorMessage: "Failed to fetch communities",
    getByIdSuccessMessage: "Community fetched successfully",
    createSuccessMessage: "Community created successfully",
    updateSuccessMessage: "Community updated successfully",
    hardDeleteSuccessMessage: "Community permanently deleted successfully",
    approveSuccessMessage: "Community approved successfully",
    rejectSuccessMessage: "Community rejected successfully",
    alreadyApprovedMessage: "Community is already approved",
    alreadyRejectedMessage: "Community is already rejected",
    isLeaf: false,
    cascadeOnActiveChange: true,
    cascadeOnDelete: true,
    userDetailsCleanup: HIERARCHY_USER_DETAILS_CLEANUP.community,
    parentApprovalChain: [],
    adminParentFields: [],
    exports: {
      create: "createCommunity",
      list: "getCommunities",
      getById: "getCommunityById",
      update: "updateCommunity",
      hardDelete: "hardDeleteCommunity",
      approve: "approveCommunity",
      reject: "rejectCommunity",
      bulkApprove: "bulkApproveCommunities",
    },
    cascade: {
      hardDelete: cascadeService.cascadeHardDeleteCommunity,
      inactive: cascadeService.cascadeInactiveCommunity,
      active: cascadeService.cascadeActiveCommunity,
    },
  },

  vansh: {
    key: "vansh",
    label: "Vansh",
    model: Vansh,
    listFilterParams: ["communityId"],
    listPopulate: [{ path: "communityId", select: "name" }],
    getByIdPopulate: [{ path: "communityId", select: "name" }],
    duplicateScopeFields: ["communityId"],
    duplicateMessage: "Vansh with this name already exists in this community",
    listSuccessMessage: "Vansh list fetched successfully",
    getByIdSuccessMessage: "Vansh fetched successfully",
    createSuccessMessage: "Vansh created successfully",
    updateSuccessMessage: "Vansh updated successfully",
    hardDeleteSuccessMessage: "Vansh permanently deleted successfully",
    approveSuccessMessage: "Vansh approved successfully",
    rejectSuccessMessage: "Vansh rejected successfully",
    alreadyApprovedMessage: "Vansh is already approved",
    alreadyRejectedMessage: "Vansh is already rejected",
    listFetchErrorMessage: "Failed to fetch vansh list",
    isLeaf: false,
    cascadeOnActiveChange: true,
    cascadeOnDelete: true,
    userDetailsCleanup: HIERARCHY_USER_DETAILS_CLEANUP.vansh,
    parentApprovalChain: [
      { level: "community", field: "communityId", model: Community },
    ],
    adminParentFields: [
      {
        field: "communityId",
        model: Community,
        label: "Community",
        notFoundMessage: "Community not found",
      },
    ],
    exports: {
      create: "createVansh",
      list: "getVanshList",
      getById: "getVanshById",
      update: "updateVansh",
      hardDelete: "hardDeleteVansh",
      approve: "approveVansh",
      reject: "rejectVansh",
      bulkApprove: "bulkApproveVansh",
    },
    cascade: {
      hardDelete: cascadeService.cascadeHardDeleteVansh,
      inactive: cascadeService.cascadeInactiveVansh,
      active: cascadeService.cascadeActiveVansh,
    },
  },

  kul: {
    key: "kul",
    label: "Kul",
    model: Kul,
    listFilterParams: ["communityId", "vanshId"],
    listPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
    ],
    getByIdPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
    ],
    duplicateScopeFields: ["vanshId"],
    duplicateMessage: "Kul with this name already exists in this vansh",
    listSuccessMessage: "Kul list fetched successfully",
    getByIdSuccessMessage: "Kul fetched successfully",
    createSuccessMessage: "Kul created successfully",
    updateSuccessMessage: "Kul updated successfully",
    hardDeleteSuccessMessage: "Kul permanently deleted successfully",
    approveSuccessMessage: "Kul approved successfully",
    rejectSuccessMessage: "Kul rejected successfully",
    alreadyApprovedMessage: "Kul is already approved",
    alreadyRejectedMessage: "Kul is already rejected",
    listFetchErrorMessage: "Failed to fetch kul list",
    isLeaf: false,
    cascadeOnActiveChange: true,
    cascadeOnDelete: true,
    userDetailsCleanup: HIERARCHY_USER_DETAILS_CLEANUP.kul,
    parentApprovalChain: [
      { level: "vansh", field: "vanshId", model: Vansh },
      { level: "community", field: "communityId", model: Community },
    ],
    adminParentFields: [
      {
        field: "communityId",
        model: Community,
        label: "Community",
        notFoundMessage: "Community not found",
      },
      {
        field: "vanshId",
        model: Vansh,
        label: "Vansh",
        notFoundMessage: "Vansh not found or does not belong to this community",
        mustMatch: { communityId: "communityId" },
      },
    ],
    exports: {
      create: "createKul",
      list: "getKulList",
      getById: "getKulById",
      update: "updateKul",
      hardDelete: "hardDeleteKul",
      approve: "approveKul",
      reject: "rejectKul",
      bulkApprove: "bulkApproveKul",
    },
    cascade: {
      hardDelete: cascadeService.cascadeHardDeleteKul,
      inactive: cascadeService.cascadeInactiveKul,
      active: cascadeService.cascadeActiveKul,
    },
  },

  khamp: {
    key: "khamp",
    label: "Khamp",
    model: Khamp,
    listFilterParams: ["communityId", "vanshId", "kulId"],
    listPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
      { path: "kulId", select: "name" },
    ],
    getByIdPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
      { path: "kulId", select: "name" },
    ],
    duplicateScopeFields: ["kulId"],
    duplicateMessage: "Khamp with this name already exists in this kul",
    listSuccessMessage: "Khamp list fetched successfully",
    getByIdSuccessMessage: "Khamp fetched successfully",
    createSuccessMessage: "Khamp created successfully",
    updateSuccessMessage: "Khamp updated successfully",
    hardDeleteSuccessMessage: "Khamp permanently deleted successfully",
    approveSuccessMessage: "Khamp approved successfully",
    rejectSuccessMessage: "Khamp rejected successfully",
    alreadyApprovedMessage: "Khamp is already approved",
    alreadyRejectedMessage: "Khamp is already rejected",
    listFetchErrorMessage: "Failed to fetch khamp list",
    isLeaf: false,
    cascadeOnActiveChange: true,
    cascadeOnDelete: true,
    userDetailsCleanup: HIERARCHY_USER_DETAILS_CLEANUP.khamp,
    parentApprovalChain: [
      { level: "kul", field: "kulId", model: Kul },
      { level: "vansh", field: "vanshId", model: Vansh },
      { level: "community", field: "communityId", model: Community },
    ],
    adminParentFields: [
      {
        field: "communityId",
        model: Community,
        label: "Community",
        notFoundMessage: "Community not found",
      },
      {
        field: "vanshId",
        model: Vansh,
        label: "Vansh",
        notFoundMessage: "Vansh not found or does not belong to this community",
        mustMatch: { communityId: "communityId" },
      },
      {
        field: "kulId",
        model: Kul,
        label: "Kul",
        notFoundMessage: "Kul not found or does not belong to this vansh",
        mustMatch: { communityId: "communityId", vanshId: "vanshId" },
      },
    ],
    exports: {
      create: "createKhamp",
      list: "getKhampList",
      getById: "getKhampById",
      update: "updateKhamp",
      hardDelete: "hardDeleteKhamp",
      approve: "approveKhamp",
      reject: "rejectKhamp",
      bulkApprove: "bulkApproveKhamp",
    },
    cascade: {
      hardDelete: cascadeService.cascadeHardDeleteKhamp,
      inactive: cascadeService.cascadeInactiveKhamp,
      active: cascadeService.cascadeActiveKhamp,
    },
  },

  subKhamp: {
    key: "subKhamp",
    label: "Sub-Khamp",
    model: SubKhamp,
    listFilterParams: ["communityId", "vanshId", "kulId", "khampId"],
    listPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
      { path: "kulId", select: "name" },
      { path: "khampId", select: "name" },
    ],
    getByIdPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
      { path: "kulId", select: "name" },
      { path: "khampId", select: "name" },
    ],
    duplicateScopeFields: ["khampId"],
    duplicateMessage: "Sub-Khamp with this name already exists in this khamp",
    listSuccessMessage: "Sub-Khamp list fetched successfully",
    getByIdSuccessMessage: "Sub-Khamp fetched successfully",
    createSuccessMessage: "Sub-Khamp created successfully",
    updateSuccessMessage: "Sub-Khamp updated successfully",
    hardDeleteSuccessMessage: "Sub-Khamp permanently deleted successfully",
    approveSuccessMessage: "Sub-Khamp approved successfully",
    rejectSuccessMessage: "Sub-Khamp rejected successfully",
    alreadyApprovedMessage: "Sub-Khamp is already approved",
    alreadyRejectedMessage: "Sub-Khamp is already rejected",
    listFetchErrorMessage: "Failed to fetch sub-khamp list",
    isLeaf: true,
    cascadeOnActiveChange: false,
    cascadeOnDelete: false,
    userDetailsCleanup: HIERARCHY_USER_DETAILS_CLEANUP.subKhamp,
    parentApprovalChain: [
      { level: "khamp", field: "khampId", model: Khamp },
      { level: "kul", field: "kulId", model: Kul },
      { level: "vansh", field: "vanshId", model: Vansh },
      { level: "community", field: "communityId", model: Community },
    ],
    adminParentFields: [
      {
        field: "communityId",
        model: Community,
        label: "Community",
        notFoundMessage: "Community not found",
      },
      {
        field: "vanshId",
        model: Vansh,
        label: "Vansh",
        notFoundMessage: "Vansh not found or does not belong to this community",
        mustMatch: { communityId: "communityId" },
      },
      {
        field: "kulId",
        model: Kul,
        label: "Kul",
        notFoundMessage: "Kul not found or does not belong to this vansh",
        mustMatch: { communityId: "communityId", vanshId: "vanshId" },
      },
      {
        field: "khampId",
        model: Khamp,
        label: "Khamp",
        notFoundMessage: "Khamp not found or does not belong to this kul",
        mustMatch: {
          communityId: "communityId",
          vanshId: "vanshId",
          kulId: "kulId",
        },
      },
    ],
    exports: {
      create: "createSubKhamp",
      list: "getSubKhampList",
      getById: "getSubKhampById",
      update: "updateSubKhamp",
      hardDelete: "hardDeleteSubKhamp",
      approve: "approveSubKhamp",
      reject: "rejectSubKhamp",
      bulkApprove: "bulkApproveSubKhamps",
    },
    cascade: {
      hardDelete: cascadeService.cascadeHardDeleteSubKhamp,
      inactive: cascadeService.cascadeInactiveSubKhamp,
      active: cascadeService.cascadeActiveSubKhamp,
    },
  },

  gotra: {
    key: "gotra",
    label: "Gotra",
    model: Gotra,
    listFilterParams: ["communityId", "vanshId", "kulId"],
    listPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
      { path: "kulId", select: "name" },
    ],
    getByIdPopulate: [
      { path: "communityId", select: "name" },
      { path: "vanshId", select: "name" },
      { path: "kulId", select: "name" },
    ],
    duplicateScopeFields: ["kulId"],
    duplicateMessage: "Gotra with this name already exists in this kul",
    listSuccessMessage: "Gotra list fetched successfully",
    getByIdSuccessMessage: "Gotra fetched successfully",
    createSuccessMessage: "Gotra created successfully",
    updateSuccessMessage: "Gotra updated successfully",
    hardDeleteSuccessMessage: "Gotra permanently deleted successfully",
    approveSuccessMessage: "Gotra approved successfully",
    rejectSuccessMessage: "Gotra rejected successfully",
    alreadyApprovedMessage: "Gotra is already approved",
    alreadyRejectedMessage: "Gotra is already rejected",
    listFetchErrorMessage: "Failed to fetch gotra list",
    isLeaf: true,
    cascadeOnActiveChange: false,
    cascadeOnDelete: false,
    userDetailsCleanup: HIERARCHY_USER_DETAILS_CLEANUP.gotra,
    parentApprovalChain: [
      { level: "kul", field: "kulId", model: Kul },
      { level: "vansh", field: "vanshId", model: Vansh },
      { level: "community", field: "communityId", model: Community },
    ],
    adminParentFields: [
      {
        field: "communityId",
        model: Community,
        label: "Community",
        notFoundMessage: "Community not found",
      },
      {
        field: "vanshId",
        model: Vansh,
        label: "Vansh",
        notFoundMessage: "Vansh not found or does not belong to this community",
        mustMatch: { communityId: "communityId" },
      },
      {
        field: "kulId",
        model: Kul,
        label: "Kul",
        notFoundMessage: "Kul not found or does not belong to this vansh",
        mustMatch: { communityId: "communityId", vanshId: "vanshId" },
      },
    ],
    exports: {
      create: "createGotra",
      list: "getGotraList",
      getById: "getGotraById",
      update: "updateGotra",
      hardDelete: "hardDeleteGotra",
      approve: "approveGotra",
      reject: "rejectGotra",
      bulkApprove: "bulkApproveGotra",
    },
    cascade: {
      hardDelete: null,
      inactive: null,
      active: null,
    },
  },
};

/**
 * User master-data dropdown/create configuration.
 */
const MASTER_DATA_ENTITIES = {
  community: {
    key: "community",
    label: "Community",
    model: Community,
    parentQueryParam: null,
    parentBodyField: null,
    parentModel: null,
    ancestorFieldsFromParent: null,
    duplicateScopeFields: [],
    duplicateMessage: "Community with this name already exists",
    listSuccessMessage: "Communities fetched successfully",
    createSuccessMessage: "Community created successfully (pending approval)",
    nameRequiredMessage: "Community name is required",
    parentRequiredMessage: null,
    parentNotFoundMessage: null,
    exports: {
      list: "getCommunities",
      create: "createCommunity",
    },
  },
  vansh: {
    key: "vansh",
    label: "Vansh",
    model: Vansh,
    parentQueryParam: "communityId",
    parentBodyField: "communityId",
    parentModel: Community,
    ancestorFieldsFromParent: null,
    duplicateScopeFields: ["communityId"],
    duplicateMessage: "Vansh with this name already exists in this community",
    listSuccessMessage: "Vanshes fetched successfully",
    createSuccessMessage: "Vansh created successfully (pending approval)",
    nameRequiredMessage: "Vansh name is required",
    parentRequiredMessage: "Valid community ID is required",
    parentNotFoundMessage: "Community not found",
    exports: {
      list: "getVanshes",
      create: "createVansh",
    },
  },
  kul: {
    key: "kul",
    label: "Kul",
    model: Kul,
    parentQueryParam: "vanshId",
    parentBodyField: "vanshId",
    parentModel: Vansh,
    ancestorFieldsFromParent: { communityId: "communityId" },
    duplicateScopeFields: ["vanshId"],
    duplicateMessage: "Kul with this name already exists in this vansh",
    listSuccessMessage: "Kuls fetched successfully",
    createSuccessMessage: "Kul created successfully (pending approval)",
    nameRequiredMessage: "Kul name is required",
    parentRequiredMessage: "Valid vansh ID is required",
    parentNotFoundMessage: "Vansh not found",
    exports: {
      list: "getKuls",
      create: "createKul",
    },
  },
  khamp: {
    key: "khamp",
    label: "Khamp",
    model: Khamp,
    parentQueryParam: "kulId",
    parentBodyField: "kulId",
    parentModel: Kul,
    ancestorFieldsFromParent: {
      communityId: "communityId",
      vanshId: "vanshId",
    },
    duplicateScopeFields: ["kulId"],
    duplicateMessage: "Khamp with this name already exists in this kul",
    listSuccessMessage: "Khamps fetched successfully",
    createSuccessMessage: "Khamp created successfully (pending approval)",
    nameRequiredMessage: "Khamp name is required",
    parentRequiredMessage: "Valid kul ID is required",
    parentNotFoundMessage: "Kul not found",
    exports: {
      list: "getKhamps",
      create: "createKhamp",
    },
  },
  subKhamp: {
    key: "subKhamp",
    label: "Sub-Khamp",
    model: SubKhamp,
    parentQueryParam: "khampId",
    parentBodyField: "khampId",
    parentModel: Khamp,
    ancestorFieldsFromParent: {
      communityId: "communityId",
      vanshId: "vanshId",
      kulId: "kulId",
    },
    duplicateScopeFields: ["khampId"],
    duplicateMessage: "Sub-Khamp with this name already exists in this khamp",
    listSuccessMessage: "Sub-Khamps fetched successfully",
    createSuccessMessage: "Sub-Khamp created successfully (pending approval)",
    nameRequiredMessage: "Sub-Khamp name is required",
    parentRequiredMessage: "Valid khamp ID is required",
    parentNotFoundMessage: "Khamp not found",
    exports: {
      list: "getSubKhamps",
      create: "createSubKhamp",
    },
  },
  gotra: {
    key: "gotra",
    label: "Gotra",
    model: Gotra,
    parentQueryParam: "kulId",
    parentBodyField: "kulId",
    parentModel: Kul,
    ancestorFieldsFromParent: {
      communityId: "communityId",
      vanshId: "vanshId",
    },
    duplicateScopeFields: ["kulId"],
    duplicateMessage: "Gotra with this name already exists in this kul",
    listSuccessMessage: "Gotras fetched successfully",
    createSuccessMessage: "Gotra created successfully (pending approval)",
    nameRequiredMessage: "Gotra name is required",
    parentRequiredMessage: "Valid kul ID is required",
    parentNotFoundMessage: "Kul not found",
    exports: {
      list: "getGotras",
      create: "createGotra",
    },
  },
};

const HIERARCHY_ENTITY_KEYS = Object.keys(HIERARCHY_ENTITIES);
const MASTER_DATA_ENTITY_KEYS = Object.keys(MASTER_DATA_ENTITIES);

module.exports = {
  HIERARCHY_ENTITIES,
  MASTER_DATA_ENTITIES,
  HIERARCHY_ENTITY_KEYS,
  MASTER_DATA_ENTITY_KEYS,
};
