import {
  communityCreated,
  resetCommunity,
  communityListUpdated,
  communityUpdated,
  communityDeleted,
  finishCommunityLoading,
  loadingOnCommunitySubmit,
  loadingCommunitiesList,
  loadingCommunity,
  communityDetailsById,
} from "@reducers/adminCommunityReducer";
import {
  vanshCreated,
  resetVansh,
  vanshListUpdated,
  vanshUpdated,
  vanshDeleted,
  finishVanshLoading,
  loadingOnVanshSubmit,
  loadingVanshList,
  loadingVansh,
  vanshDetailsById,
} from "@reducers/adminVanshReducer";
import {
  kulCreated,
  resetKul,
  kulListUpdated,
  kulUpdated,
  kulDeleted,
  finishKulLoading,
  loadingOnKulSubmit,
  loadingKulList,
  loadingKul,
  kulDetailsById,
} from "@reducers/adminKulReducer";
import {
  khampCreated,
  resetKhamp,
  khampListUpdated,
  khampUpdated,
  khampDeleted,
  finishKhampLoading,
  loadingOnKhampSubmit,
  loadingKhampList,
  loadingKhamp,
  khampDetailsById,
} from "@reducers/adminKhampReducer";
import {
  subKhampCreated,
  resetSubKhamp,
  subKhampListUpdated,
  subKhampUpdated,
  subKhampDeleted,
  finishSubKhampLoading,
  loadingOnSubKhampSubmit,
  loadingSubKhampList,
  loadingSubKhamp,
  subKhampDetailsById,
} from "@reducers/adminSubKhampReducer";
import {
  gotraCreated,
  resetGotra,
  gotraListUpdated,
  gotraUpdated,
  gotraDeleted,
  finishGotraLoading,
  loadingOnGotraSubmit,
  loadingGotraList,
  loadingGotra,
  gotraDetailsById,
} from "@reducers/adminGotraReducer";

const CM_BASE = "/admin/community-management";
export const HIERARCHY_ADMIN_ENTITIES = {
  community: {
    key: "community",
    label: "Community",
    labelPlural: "Communities",
    permissionModule: "communities",
    apiPath: "/api/admin/communities",
    listRoute: `${CM_BASE}/community`,
    reduxSlice: "community",
    listStateKey: "communityList",
    currentStateKey: "currentCommunity",
    loadingListKey: "loadingCommunitiesList",
    loadingEntityKey: "loadingCommunity",
    parentColumns: [],
    formParents: [],
    reducers: {
      created: communityCreated,
      reset: resetCommunity,
      updated: communityUpdated,
      deleted: communityDeleted,
      finishLoading: finishCommunityLoading,
      listUpdated: communityListUpdated,
      detailsById: communityDetailsById,
      loadingSubmit: loadingOnCommunitySubmit,
      loadingList: loadingCommunitiesList,
      loadingEntity: loadingCommunity,
    },
    exportNames: {
      list: "getCommunities",
      getById: "getCommunityById",
      create: "createCommunity",
      update: "updateCommunity",
      hardDelete: "hardDeleteCommunity",
      resetStore: "resetComponentStore",
    },
  },

  vansh: {
    key: "vansh",
    label: "Vansh",
    labelPlural: "Vansh",
    permissionModule: "vansh",
    apiPath: "/api/admin/vansh",
    listRoute: `${CM_BASE}/vansh`,
    reduxSlice: "vansh",
    listStateKey: "vanshList",
    currentStateKey: "currentVansh",
    loadingListKey: "loadingVanshList",
    loadingEntityKey: "loadingVansh",
    parentColumns: [
      {
        label: "Community",
        accessor: (row) => row.communityId?.name || "-",
      },
    ],
    formParents: [
      { field: "communityId", label: "Community", fetchKey: "communities" },
    ],
    reducers: {
      created: vanshCreated,
      reset: resetVansh,
      updated: vanshUpdated,
      deleted: vanshDeleted,
      finishLoading: finishVanshLoading,
      listUpdated: vanshListUpdated,
      detailsById: vanshDetailsById,
      loadingSubmit: loadingOnVanshSubmit,
      loadingList: loadingVanshList,
      loadingEntity: loadingVansh,
    },
    exportNames: {
      list: "getVanshList",
      getById: "getVanshById",
      create: "createVansh",
      update: "updateVansh",
      hardDelete: "hardDeleteVansh",
      resetStore: "resetComponentStore",
    },
  },

  kul: {
    key: "kul",
    label: "Kul",
    labelPlural: "Kul",
    permissionModule: "kul",
    apiPath: "/api/admin/kul",
    listRoute: `${CM_BASE}/kul`,
    reduxSlice: "kul",
    listStateKey: "kulList",
    currentStateKey: "currentKul",
    loadingListKey: "loadingKulList",
    loadingEntityKey: "loadingKul",
    parentColumns: [
      { label: "Community", accessor: (row) => row.communityId?.name || "-" },
      { label: "Vansh", accessor: (row) => row.vanshId?.name || "-" },
    ],
    formParents: [
      { field: "communityId", label: "Community", fetchKey: "communities" },
      {
        field: "vanshId",
        label: "Vansh",
        fetchKey: "vanshes",
        dependsOn: "communityId",
      },
    ],
    reducers: {
      created: kulCreated,
      reset: resetKul,
      updated: kulUpdated,
      deleted: kulDeleted,
      finishLoading: finishKulLoading,
      listUpdated: kulListUpdated,
      detailsById: kulDetailsById,
      loadingSubmit: loadingOnKulSubmit,
      loadingList: loadingKulList,
      loadingEntity: loadingKul,
    },
    exportNames: {
      list: "getKulList",
      getById: "getKulById",
      create: "createKul",
      update: "updateKul",
      hardDelete: "hardDeleteKul",
      resetStore: "resetComponentStore",
    },
  },

  khamp: {
    key: "khamp",
    label: "Khamp",
    labelPlural: "Khamp",
    permissionModule: "khamp",
    apiPath: "/api/admin/khamp",
    listRoute: `${CM_BASE}/khamp`,
    reduxSlice: "khamp",
    listStateKey: "khampList",
    currentStateKey: "currentKhamp",
    loadingListKey: "loadingKhampList",
    loadingEntityKey: "loadingKhamp",
    parentColumns: [
      { label: "Community", accessor: (row) => row.communityId?.name || "-" },
      { label: "Vansh", accessor: (row) => row.vanshId?.name || "-" },
      { label: "Kul", accessor: (row) => row.kulId?.name || "-" },
    ],
    formParents: [
      { field: "communityId", label: "Community", fetchKey: "communities" },
      {
        field: "vanshId",
        label: "Vansh",
        fetchKey: "vanshes",
        dependsOn: "communityId",
      },
      { field: "kulId", label: "Kul", fetchKey: "kuls", dependsOn: "vanshId" },
    ],
    reducers: {
      created: khampCreated,
      reset: resetKhamp,
      updated: khampUpdated,
      deleted: khampDeleted,
      finishLoading: finishKhampLoading,
      listUpdated: khampListUpdated,
      detailsById: khampDetailsById,
      loadingSubmit: loadingOnKhampSubmit,
      loadingList: loadingKhampList,
      loadingEntity: loadingKhamp,
    },
    exportNames: {
      list: "getKhampList",
      getById: "getKhampById",
      create: "createKhamp",
      update: "updateKhamp",
      hardDelete: "hardDeleteKhamp",
      resetStore: "resetComponentStore",
    },
  },

  subKhamp: {
    key: "subKhamp",
    label: "Sub-Khamp",
    labelPlural: "Sub-Khamp",
    permissionModule: "subKhamp",
    apiPath: "/api/admin/sub-khamp",
    listRoute: `${CM_BASE}/subKhamp`,
    reduxSlice: "subKhamp",
    listStateKey: "subKhampList",
    currentStateKey: "currentSubKhamp",
    loadingListKey: "loadingSubKhampList",
    loadingEntityKey: "loadingSubKhamp",
    parentColumns: [
      { label: "Community", accessor: (row) => row.communityId?.name || "-" },
      { label: "Vansh", accessor: (row) => row.vanshId?.name || "-" },
      { label: "Kul", accessor: (row) => row.kulId?.name || "-" },
      { label: "Khamp", accessor: (row) => row.khampId?.name || "-" },
    ],
    formParents: [
      { field: "communityId", label: "Community", fetchKey: "communities" },
      {
        field: "vanshId",
        label: "Vansh",
        fetchKey: "vanshes",
        dependsOn: "communityId",
      },
      { field: "kulId", label: "Kul", fetchKey: "kuls", dependsOn: "vanshId" },
      {
        field: "khampId",
        label: "Khamp",
        fetchKey: "khamps",
        dependsOn: "kulId",
      },
    ],
    reducers: {
      created: subKhampCreated,
      reset: resetSubKhamp,
      updated: subKhampUpdated,
      deleted: subKhampDeleted,
      finishLoading: finishSubKhampLoading,
      listUpdated: subKhampListUpdated,
      detailsById: subKhampDetailsById,
      loadingSubmit: loadingOnSubKhampSubmit,
      loadingList: loadingSubKhampList,
      loadingEntity: loadingSubKhamp,
    },
    exportNames: {
      list: "getSubKhampList",
      getById: "getSubKhampById",
      create: "createSubKhamp",
      update: "updateSubKhamp",
      hardDelete: "hardDeleteSubKhamp",
      resetStore: "resetComponentStore",
    },
  },

  gotra: {
    key: "gotra",
    label: "Gotra",
    labelPlural: "Gotra",
    permissionModule: "gotra",
    apiPath: "/api/admin/gotra",
    listRoute: `${CM_BASE}/gotra`,
    reduxSlice: "gotra",
    listStateKey: "gotraList",
    currentStateKey: "currentGotra",
    loadingListKey: "loadingGotraList",
    loadingEntityKey: "loadingGotra",
    parentColumns: [
      { label: "Community", accessor: (row) => row.communityId?.name || "-" },
      { label: "Vansh", accessor: (row) => row.vanshId?.name || "-" },
      { label: "Kul", accessor: (row) => row.kulId?.name || "-" },
    ],
    formParents: [
      { field: "communityId", label: "Community", fetchKey: "communities" },
      {
        field: "vanshId",
        label: "Vansh",
        fetchKey: "vanshes",
        dependsOn: "communityId",
      },
      { field: "kulId", label: "Kul", fetchKey: "kuls", dependsOn: "vanshId" },
    ],
    reducers: {
      created: gotraCreated,
      reset: resetGotra,
      updated: gotraUpdated,
      deleted: gotraDeleted,
      finishLoading: finishGotraLoading,
      listUpdated: gotraListUpdated,
      detailsById: gotraDetailsById,
      loadingSubmit: loadingOnGotraSubmit,
      loadingList: loadingGotraList,
      loadingEntity: loadingGotra,
    },
    exportNames: {
      list: "getGotraList",
      getById: "getGotraById",
      create: "createGotra",
      update: "updateGotra",
      hardDelete: "hardDeleteGotra",
      resetStore: "resetComponentStore",
    },
  },
};
